web_content/online_shop/v1/routes/auth.py
# /usr/bin/python3
""" app module """
from flask import (
    Flask,
    render_template,
    request,
    redirect,
    url_for,
    jsonify,
    make_response,
    current_app,
)
from flask_login import (
    UserMixin,
    login_user,
    LoginManager,
    login_required,
    logout_user,
    current_user,
)
from web_content.online_shop.v1.routes.forms import RegisterForm
from web_content.online_shop.v1.routes.forms import LoginForm
from web_content.online_shop.v1.routes.store import app_store
from models.user import User

# from web_flask.version01.models import User
from models import storage
from web_content.online_shop.v1.app import db, bcrypt
from flask import Blueprint, session, request
import uuid


app_auth = Blueprint("app_auth", __name__, url_prefix="/auth/v1")


@app_auth.route("/register", methods=["GET", "POST"], strict_slashes=False)
def register():
    cache_id = str(uuid.uuid4())
    form = RegisterForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data)
        new_user = User()
        new_user.first_name = form.firstname.data
        new_user.last_name = form.lastname.data
        new_user.email = form.email.data
        new_user.password = hashed_password
        """
        with current_app.app_context():
            db.session.add(new_user)
            db.session.commit()
        """
        storage.new(new_user)
        storage.save()
        return redirect(url_for("app_auth.login"))

    return render_template("register.html", form=form, cache_id=cache_id)


@app_auth.route("/login", methods=["GET", "POST"], strict_slashes=False)
def login():
    form = LoginForm()
    cache_id = str(uuid.uuid4())

    if form.validate_on_submit():
        user = storage.user_by_email(form.email.data)
        #remember = True if request.form.get('remember') else False
        if user:
            if bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)
                default_cart = storage.serve_user(user)
                session['cart'] = default_cart.to_dict()
                return redirect(url_for("app_store.landing_page", form=form))
    return render_template("login.html", form=form, cache_id=cache_id)


@app_auth.route("/logout", methods=["GET", "POST"], strict_slashes=False)
@login_required
def logout():
    logout_user()
    return redirect(url_for("app_auth.login"))


@app_auth.route("/dashboard", methods=["GET", "POST"], strict_slashes=False)
@login_required
def dashboard():
    form = LoginForm()

    return render_template("dashboard.html", form=form)

web_content/online_shop/v1/templates/about_us.html
{% extends "base.html" %}

{% block content %}
<div class="front-img" style="background-image: url('static/images/Green-Ecommerce.png');">
  <h1>About GebeyaHUB</h1>
</div>
<div class="wrapper">
  <h2><i class="fas fa-shopping-cart"></i>GebeyaHUB</h2>
  <p>
  GebeyaHUB is an online platform that aims to revolutionize the way people shop and trade in Ethiopia by connecting buyers and sellers from across the country. This project is our own initiative and not just a requirement from Holberton School. It serves as a Portfolio Project for Holberton School, showcasing our skills and expertise in web development.
  </p>
  <h2><i class="fas fa-lightbulb"></i>Inspiration</h2>
  <p>
  The inspiration behind GebeyaHUB comes from our deep understanding of the Ethiopian marketplace and the potential for digital transformation in the country. We have witnessed firsthand the challenges faced by individuals and businesses in accessing a diverse range of products and services. Limited access to markets, geographic barriers, and inefficient trading practices have hindered the growth of businesses and constrained consumer choices.
  </p>
  <p>
  Motivated by the desire to address these challenges, we embarked on developing GebeyaHUB. Our goal is to create an inclusive and convenient platform that bridges the gap between buyers and sellers, providing them with a seamless online shopping and trading experience. We believe that by leveraging technology, we can empower individuals and businesses to thrive in Ethiopia's vibrant marketplace.
  </p>

  <h2><i class="fas fa-hands-helping"></i>Collaborative Approach</h2>
  <p>
  As a cohesive team, consisting of Nathan Assefa Kassa and Mahlet Seifu Feleke, we have been working closely together throughout the development process of the GebeyaHUB project. Although our roles are not strictly divided, we contribute to various aspects of the project, including development, design, and user experience.
  </p>

  <p>
  Working as a dedicated team, we bring together our unique skills and synergy to ensure the delivery of a high-quality e-commerce website. By developing our own solution, we have the flexibility to incorporate any unique features or design elements that we believe will enhance the user experience. Our aim is to showcase our problem-solving skills, apply best practices, and utilize modern technologies while keeping the project scope manageable and aligned with our portfolio goals.
  </p>
  <div class="team-members">
    <h2><i class="fas fa-users"></i>Team Members</h2>
    <div class="columns">
    <ul class="team">
      <li class="members">
        <a href="https://www.linkedin.com/in/nathan-assefa-9ba017253/" target="_blank"><i class="fab fa-linkedin"></i>Nathan Assefa Kassa - LinkedIn</a>
        <a href="https://github.com/nathan-assefa" target="_blank"><i class="fab fa-github"></i>Github</a>
        <a href="https://twitter.com/nathanassefa" target="_blank"><i class="fab fa-twitter"></i>Twitter</a>
      </li>
      <li class="members">
        <a href="https://www.linkedin.com/in/mahlet-seifu-feleke" target="_blank"><i class="fab fa-linkedin"></i>Mahlet Seifu Feleke - LinkedIn</a>
        <a href="https://github.com/Mahlet2123" target="_blank"><i class="fab fa-github"></i>Github</a>
        <a href="https://twitter.com/mahletseifu21" target="_blank"><i class="fab fa-twitter"></i>Twitter</a>
      </li>
    </ul>
    </div>
  </div>

  <div class="github-repo">
    <h2><i class="fab fa-github"></i>GitHub Repository</h2>
    <p>
      You can find the project's source code on GitHub:
      <a href="https://github.com/nathan-assefa/Online_store" target="_blank">GebeyaHUB Repository</a>
    </p>
  </div>
</div>
  <style>
    /* Add some basic styling */
    body {
      width: 100%;
      box-sizing: border-box;
    }

    .wrapper {
      text-align: center;
      width: 85%;
      margin-bottom: 9em;
      font-family: Poppins;
      margin-left: auto;
      margin-right: auto;
     }

    h1 {
      text-align: left;
    }

    .front-img {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 300px;
      background-size: cover;
      background-position: center;
      background-repeat: no-repeat;
      margin-bottom: 2px;
    }

    .front-img h1 {
      color: black;
      font-size: 36px;
      text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
      text-align: left;
    }

    p {
      text-align: justify;
      word-spacing: .1em;
    }

    h2 {
      font-size: 24px;
      margin-bottom: 10px;
      display: flex;
      align-items: center;
    }

    h2 i {
      margin-right: 10px;
    }

    p {
      text-align: justify;
      font-size: 16px;
      line-height: 1.5;
      margin-bottom: 20px;
    }

    .members {
      margin-bottom: 10px;
    }

    .members a {
      display: inline-block;
      color: #333;
      text-decoration: none;
      margin-right: 10px;
    }

    .members a i {
      margin-right: 10px;
    }

    .columns .members{
      display: flex;
      flex-direction: column;
      justify-content: space-evenly;
      gap: 20px;
    }

    .team {
      display: flex;
      list-style-type: none;
      padding: 0;
      flex: 1;
      margin-right: 20px;
      margin-top: 20px;
    }

    .team ul li {
      margin-bottom: 10px;
    }
  </style>
  {% endblock %} 

web_content/online_shop/v1/templates/all_product.html
<link rel="stylesheet" href="{{ url_for('static', filename='styles/all_product.css') }}">
    {% extends "base.html" %}

    {% block content %}

    <div class='body'>
      <div class="card--container new--cart" data-cart="{{ cart }}">
	{% for product in products|sort(attribute='sort_key') %}
        <div class='card'>
          <div class='card-content'>
            <div class='img'>
		    <a href="/store/v1/item/{{ product.id }}"><img src='{{ product.image }}'></a>
            </div>
          </div>
          <div class='card-detail'>
            <div class='title'>
		    {{ product.name }}
            </div>
	    <p class="truncated description">{{ product.description }}</p>
            <div class="price--info">
		    $<span class="price">{{ product.price }}</span>
            </div>
            <div class="cta-btns">
		    <a href="/store/v1/item/{{ product.id }}" class="secondary-cta ml-3" id="{{ product.id }}">
                  	<span>View More</span>
                  	<svg viewBox="0 0 19 8" fill="none">
                      		<path d="M18.3536 4.35355C18.5488 4.15829 18.5488 3.84171 18.3536 3.64645L15.1716 0.464466C14.9763 0.269204 14.6597 0.269204 14.4645 0.464466C14.2692 0.659728 14.2692 0.976311 14.4645 1.17157L17.2929 4L14.4645 6.82843C14.2692 7.02369 14.2692 7.34027 14.4645 7.53553C14.6597 7.7308 14.9763 7.7308 15.1716 7.53553L18.3536 4.35355ZM0 4.5H18V3.5H0V4.5Z" fill="black"/>
                  </svg>
              </a>
            </div>
          </div>
        </div>
	{% endfor %}
      </div>
    </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.min.js" integrity="sha512-lOrm9FgT1LKOJRUXF3tp6QaMorJftUjowOWiDcG5GFZ/q7ukof19V0HKx/GWzXCdt9zYju3/KhBNdCLzK8b90Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  {% endblock %}

web_content/online_shop/v1/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GebeyaHub</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.css" integrity="sha512-NXUhxhkDgZYOMjaIgd89zF2w51Mub53Ru3zCNp5LTlEzMbNNAjTjDbpURYGS5Mop2cU4b7re1nOIucsVlrx9fA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&family=Poppins:wght@200;400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,700;1,400&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/landing_page.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/footer.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/header.css') }}">
    <script type="text/javascript" src="{{ url_for('static', filename='scripts/cart.js') }}"></script>
</head>
<body>
    <div class="header--wrapper">
    <a href='/store/v1/cart'><div class="number--of--items">0</div></a>
    <div class="auth">
	  <a href='/auth/v1/login'><button class="signin">Sign in</button></a>
	  <a href="/store/v1/cart"><img src="{{ url_for('static', filename='images/cart_icon.png') }}" alt="" class="cart"></a>
    </div>
    <div class="wrapper--base">
        <header>
            <a href="/store/v1/" class="logo">Gebeya<span>Hub</span></a>
            <nav class="nav">
                <svg id="close" class="close" viewBox="0 0 33 33" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M16.5 0.25C13.2861 0.25 10.1443 1.20305 7.47199 2.98862C4.79969 4.77419 2.71689 7.31209 1.48697 10.2814C0.257041 13.2507 -0.0647633 16.518 0.562247 19.6702C1.18926 22.8224 2.73692 25.7179 5.00952 27.9905C7.28213 30.2631 10.1776 31.8108 13.3298 32.4378C16.482 33.0648 19.7493 32.743 22.7186 31.513C25.6879 30.2831 28.2258 28.2003 30.0114 25.528C31.797 22.8557 32.75 19.7139 32.75 16.5C32.75 14.366 32.3297 12.2529 31.5131 10.2814C30.6964 8.30985 29.4994 6.51847 27.9905 5.00952C26.4815 3.50056 24.6902 2.3036 22.7186 1.48696C20.7471 0.670319 18.634 0.25 16.5 0.25V0.25ZM20.9038 18.5963C21.0561 18.7473 21.177 18.927 21.2595 19.1251C21.342 19.3231 21.3844 19.5355 21.3844 19.75C21.3844 19.9645 21.342 20.1769 21.2595 20.3749C21.177 20.573 21.0561 20.7527 20.9038 20.9038C20.7527 21.0561 20.573 21.177 20.3749 21.2594C20.1769 21.3419 19.9645 21.3844 19.75 21.3844C19.5355 21.3844 19.3231 21.3419 19.1251 21.2594C18.9271 21.177 18.7473 21.0561 18.5963 20.9038L16.5 18.7913L14.4038 20.9038C14.2527 21.0561 14.073 21.177 13.8749 21.2594C13.6769 21.3419 13.4645 21.3844 13.25 21.3844C13.0355 21.3844 12.8231 21.3419 12.6251 21.2594C12.427 21.177 12.2473 21.0561 12.0963 20.9038C11.9439 20.7527 11.8231 20.573 11.7406 20.3749C11.6581 20.1769 11.6156 19.9645 11.6156 19.75C11.6156 19.5355 11.6581 19.3231 11.7406 19.1251C11.8231 18.927 11.9439 18.7473 12.0963 18.5963L14.2088 16.5L12.0963 14.4038C11.7903 14.0978 11.6184 13.6827 11.6184 13.25C11.6184 12.8173 11.7903 12.4022 12.0963 12.0963C12.4023 11.7903 12.8173 11.6184 13.25 11.6184C13.6827 11.6184 14.0978 11.7903 14.4038 12.0963L16.5 14.2088L18.5963 12.0963C18.9023 11.7903 19.3173 11.6184 19.75 11.6184C20.1827 11.6184 20.5978 11.7903 20.9038 12.0963C21.2098 12.4022 21.3817 12.8173 21.3817 13.25C21.3817 13.6827 21.2098 14.0978 20.9038 14.4038L18.7913 16.5L20.9038 18.5963Z" fill="black"/>
                </svg>
		<ul class="primary-nav">
                    <li><a href="/store/v1/" class="active">Home</a></li>
                    <li class="dropdown"><a href="/store/v1/items">Products</a></li>
                    <li class="about--us"><a href="/store/v1/about_us">About Us</a></li>
		</ul>
            </nav>
            <svg id="menu" class="menu" viewBox="0 0 48 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M24 32H0V26.6667H24V32ZM48 18.6667H0V13.3333H48V18.6667ZM48 5.33333H24V0H48V5.33333Z" fill="white"/>
            </svg>
        </header>
    </div>
    </div>
    {% block content %}
    {% endblock %}
    <footer>
        <div class="footer-container">
            <div class="container">
                <a href="/store/v1/">
                    <div class="fut"><p>Gebeya<span>Hub</span></p></div>
                </a>
                <p class="address">Lideta, Addis Ababa<br>Ethiopia</p>
                <ul class="footer-links">
                    <li><a href="#">Terms of Service</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                </ul>
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js"></script>
    <script>
        const menu = document.querySelector('.menu')
        const close = document.querySelector('.close')
        const nav = document.querySelector('nav')

        menu.addEventListener('click', () => {
            nav.classList.add('open--nav')
        })

        close.addEventListener('click', () => {
            nav.classList.remove('open--nav')
        })
    </script>
</body>
</html>

web_content/online_shop/v1/templates/cart.html
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/cart.css') }}?cache_id={{ cache_id }}">
  {% extends "base.html" %}

  {% block content %}
  <script type="text/javascript" src="{{ url_for('static', filename='scripts/cart.js') }}"></script>
    <div class="container--cart new--cart" data-cart="{{ cart }}"></div>
    <div class='header'>
      <div class='title'>
        <p>
          <a href="#" class="clear_cart"><i class="far fa-trash-alt"></i></a>
        </p>
      </div>
    </div>
    <body>
     <div id="wrapper">
      <div class="flex">
        <p>
          Total Amount:
        </p>
        <p>
          <span class="total_amount"></span>
          <a href="">Order</a>
        </p>
      </div>
      <table id="keywords" cellspacing="0" cellpadding="0">
        <thead>
          <tr>
            <th><span>Name</span></th>
            <th><span>Quantity</span></th>
            <th><span>Price</span></th>
            <th><span>Total Price</span></th>
	    <th><span>Increment</span></th>
	    <th><span>Decrement</span></th>
	    <th><span>Remove</span></th>
          </tr>
        </thead>
        <tbody>
          
        </tbody>
      </table>
     </div> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.min.js" integrity="sha512-lOrm9FgT1LKOJRUXF3tp6QaMorJftUjowOWiDcG5GFZ/q7ukof19V0HKx/GWzXCdt9zYju3/KhBNdCLzK8b90Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <div>trying</div>
    {% endblock %}

web_content/online_shop/v1/templates/categories.html
<link rel="stylesheet" href="/static/styles/categories.css">
{% extends "base.html" %}

{% block content %}
    <div class="products--in--categry">
        {% for product in products %}
           <div class="item--wrap">
                <div class="img--wrap">
                    <a href="/store/v1/item/{{ product.id }}"><img src="{{ product.image }}" alt="" class="category--img"></a>
                </div>
                <p class="item--descriptioin">{{ product.description }}</p>
                <div class="category--item--price">${{ product.price }}</div>
                <a href="/store/v1/item/{{ product.id }}" class="category--item--btn"><button>explore</button></a>
           </div>
        {% endfor %}
    </div>
{% endblock %}

web_content/online_shop/v1/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Dashboard</title>
    </head>
    <body>
        <h1>The Dashboard</h1>
        <h1>Hey, you are logged in!</h1>
        <h1>--------------------------------------------</h1>
        <a href="{{ url_for('app_auth.logout')}}">Logout</a>
    </body>
</html>

web_content/online_shop/v1/templates/landing_page.html
    {% extends "base.html" %}

    {% block content %}    
    <div class="swiper new--cart swiper--for--landing" data-cart="{{ cart }}">
        <!-- Additional required wrapper -->
        <div class="swiper-wrapper">
            <!-- Slides -->
	    <div class="swiper-slide"><img src="{{ url_for('static', filename='images/Landing_page_image-01.jpg') }}"></div>
	    <div class="swiper-slide"><img src="{{ url_for('static', filename='images/Landing_page_image-02.jpg') }}"></div>
	    <div class="swiper-slide"><img src="{{ url_for('static', filename='images/Landing_page_image-03.jpg') }}"></div>
	    <div class="swiper-slide"><img src="{{ url_for('static', filename='images/Landing_page_image-04.jpg') }}"></div>
        </div>
        <!-- If we need pagination -->
        <div class="swiper-pagination"></div>
        <!-- If we need navigation buttons -->
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
    </div>
    <div class="wrapper">
    <main>
        <div class="left-col">
            <div class="news">
                <p class="employees">30%</p>
                <p class="details">
                    Discover the Best Deals" - Highlighting that GebeyaHub offers <strong>30%</strong> discount.
                    Attractive discounts and competitive prices..
                </p>
            </div>
            <div class="cta-btn">
                <a href="/store/v1/items" class="prim-cta">Browse our collection</a>
                <a href="/auth/v1/login" class="sec-cta">
                    <span>Signin Now</span>
                    <svg viewBox="0 0 19 8" fill="none">
                        <path d="M18.3536 4.35355C18.5488 4.15829 18.5488 3.84171 18.3536 3.64645L15.1716 0.464466C14.9763 0.269204 14.6597 0.269204 14.4645 0.464466C14.2692 0.659728 14.2692 0.976311 14.4645 1.17157L17.2929 4L14.4645 6.82843C14.2692 7.02369 14.2692 7.34027 14.4645 7.53553C14.6597 7.7308 14.9763 7.7308 15.1716 7.53553L18.3536 4.35355ZM0 4.5H18V3.5H0V4.5Z" fill="black"/>
                    </svg>
                </a>
            </div>
        </div>
        <div class="right-col">
	    <div style="background-image: url('{{ url_for('static', filename='images/items0A.jpg') }}')" class="picture card1">
                <div class="card-details">
                    <div>
				        <a href="/store/v1/items" class="product-title">Discover More</a>
                    </div>
                </div>
            </div>
	    <div style="background-image: url('{{ url_for('static', filename='images/items0C.jpg') }}')" class="picture card2">
            </div>
	    <div style="background-image: url('{{ url_for('static', filename='images/items0D.jpg') }}')" class="picture card3">
            </div>
        </div>
    </main>
    </div>
    <div class="blue-container">
        <div class="container--2">
            <ul>
		<li>
                        <a href="/store/v1/category/shoe"><i class="fas fa-shoe-prints category-icon"></i></a>
                        <span class="category-name">Shoes</span>
                </li>
                <li>
                        <a href="/store/v1/category/dressings"><i class="fas fa-tshirt category-icon"></i></a>
                        <span class="category-name">Dressings</span>
                </li>
                <li>
                        <a href="/store/v1/category/jewelry"><i class="fas fa-gem category-icon"></i></a>
                        <span class="category-name">Jewelry</span>
                </li>
                <li>
                        <a href="/store/v1/category/tech"><i class="fas fa-laptop category-icon"></i></a>
                        <span class="category-name">Tech Items</span>
                </li>
            </ul>
        </div>
    </div>
    <div class="gray-container">
        <div class="container--2">
            <ul>
                <li>
                    <figure>
			    <img class="testimony--img" src="{{ url_for('static', filename='images/mahi.jpg') }}" alt="User testimonial picture">
                        <blockquote>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas tenetur totam, dolore</blockquote>
                        <figcaption>- Mahlet Seifu</figcaption>
                    </figure>
                </li>
                <li>
                    <figure>
			    <img class="testimony--img" src="{{ url_for('static', filename='images/nathan.jpg') }}" alt="User testimonial picture">
                        <blockquote>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas tenetur totam, dolore</blockquote>
                        <figcaption>- Nathan Assefa</figcaption>
                    </figure>
                </li>
            </ul>
        </div>
    </div>

    <!-- ***** Contact Area Starts ***** -->
    <section class="contact-section">
        <div class="container--2">
            <div class="contact-left">
                <h2>Contact</h2>

                <form action="">
                    <label for="name">Name</label>
                    <input type="text" id="name" name="name">

                    <label for="message">Message</label>
                    <textarea name="message" id="message" cols="30" rows="10"></textarea>
                    <input type="submit" class="send-message-cta" value="Send message">
                </form>
            </div>
            <div class="contact-right">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26430.393553120906!2d-118.43209796322542!3d34.10028430183922!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2bc35fbd217ef%3A0xcf1ef9352700d95c!2sBeverly%20Hills%2C%20CA%2090210!5e0!3m2!1sen!2sus!4v1611702818717!5m2!1sen!2sus" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </div>

        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js"></script>
    <script>
        const swiper = new Swiper('.swiper', {
            autoplay: {
                delay: 6000,
                disableOnInteraction: false,
            },
            loop: true,

        // If we need pagination
            pagination: {
                el: '.swiper-pagination',
                clickable: true,
            },

            // Navigation arrows
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },
        });

        const menu = document.querySelector('.menu')
        const close = document.querySelector('.close')
        const nav = document.querySelector('nav')

        menu.addEventListener('click', () => {
            nav.classList.add('open--nav')
        })

        close.addEventListener('click', () => {
            nav.classList.remove('open--nav')
        })
    </script>
    {% endblock %}

web_content/online_shop/v1/templates/login.html
        <link rel="stylesheet" href="/static/styles/login_style.css?cache_id={{ cache_id }}">
	{% extends "base.html" %}

    	{% block content %}
	<body style="background-image: url('/static/images/bg-registration-form-2.jpg');">
        <div class="wrapper">
            <div class="inner">
    	    	<form action="" method="POST">
                    <h3>Login Form</h3>
		    	    {{ form.hidden_tag() }}
                    <div class="form-wrapper">
                        <!-- User Name input -->
                        {{ form.email }}
                        {% if form.email.errors %}
                            {% for error in form.email.errors %}
                            <p class="error">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="form-wrapper">
    		 	        <!-- Password input -->
	    	            {{ form.password }}
                        {% if form.password.errors %}
                            {% for error in form.email.errors %}
                            <p class="error">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div>
                        <!-- Checkbox -->
                        {{ form.remember() }} {{ form.remember.label }} 
                    </div>
                    <!-- Submit button -->
                    {{ form.submit}}
					<div>
						<p>Not a member? <a href="{{url_for('app_auth.register')}}">Register</a></p>
					</div>
    	    	</form>
            </div>
        </div>
	{% endblock %}